import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import OtobusHatlari from "@/components/OtobusHatlari/OtobusHatlari";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const getDownloads = async () => {
    fetch("/api/crawler").then(function(response) { return response.text(); })
    .then(function(text) {
        console.log(text)
    });
  }


    useEffect(() => {
      console.log("jashdjsahd")
        getDownloads();

    }, [])

  return (
    <>
      <Head>
        <title>Otobüsüm Nerede</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <OtobusHatlari />
    </>
  );
}
