import Head from "next/head";
import { useEffect } from "react";
import OtobusHatlari from "@/components/OtobusHatlari/OtobusHatlari";

export default function Home() {
  const getDownloads = async () => {
    fetch("/api/crawler").then(function(response) { return response.text(); })
    .then(function(text) {
        console.log(text)
    });
  }


    useEffect(() => {
      console.log("jashdjsahd")
        getDownloads();

    }, [])

  return (
    <>
      <Head>
        <title>Otobüsüm Nerede</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <OtobusHatlari />
    </>
  );
}
